name: ReleaseBuild
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: ReleaseBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: CreatePackage
        run: ./.github/UnityPacker.exe Packages/com.kakunvr.facial-lock-generator ExportedPackage
      
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ExportedPackage.unitypackage
          path: ExportedPackage.unitypackage
