name: ReleaseBuild
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: ReleaseBuild
    runs-on: ubuntu-latest
    env:
      VERSION: 0.0.1
    steps:
      - uses: actions/checkout@v2

      # バージョン値を書き換える


      - name: CreatePackage
        run: ./.github/UnityPacker.exe Packages/com.kakunvr.facial-lock-generator ExportedPackage

      # Booth配布用のzipを作成する
      - name: Create Booth Package
        run: |
          mv Docs/ FacialLockGenerator-$VERSION/
          cp LICENCE FacialLockGenerator-$VERSION/
          cp ExportedPackage.unitypackage FacialLockGenerator-$VERSION/FacialLockGenerator-$VERSION.unitypackage
          zip FacialLockGenerator-$VERSION.zip FacialLockGenerator-$VERSION/*
          mv FacialLockGenerator-$VERSION.zip FacialLockGenerator-$VERSION-booth.zip

      # VCC用のzipを作成する
      - name: Create VCC Package
        run: |
          zip Packages/com.kakunvr.facial-lock-generator com.kakunvr.facial-lock-generator-$VERSION.zip
      
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FacialLockGenerator
          path: FacialLockGenerator-*.zip
