name: ReleaseBuild
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: ReleaseBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/cache@v2
        with:
          path: ./Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-

      - name: ExportUnityPackage
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: ExportPackage.CreatePackage
          unityVersion: 2019.4.31f1
          targetPlatform: StandaloneWindows
      
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ExportedPackage.unitypackage
          path: ExportedPackage.unitypackage
